version: 0.7.2.{build}
build_script:
- ps: >-
    choco install dotnetcore -version 2.0.0

    dotnet restore LiteApi/LiteApi.sln

    dotnet build LiteApi/LiteApi.sln
test_script:
- ps: >-
    .\runtests.ps1
